language: java
jdk:
  - openjdk11

branches:
  only:
    - main

before_install:
  - cd ./TodoApplication/back/demo
  - chmod +x gradlew


before_script:
  - cd TodoApplication/back/demo/


# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew bootRun"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - seol11796@gmail.com


